CREATE TABLE user_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id VARCHAR(50) NOT NULL,
    activity_type VARCHAR(50),
    payload TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Note: Initially, we do NOT add an index on tracking_id to demonstrate the performance bottleneck.
