package com.interview.debug.controller;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/scenario57")
public class Scenario57Controller {

    /**
     * Demonstrates CSP in action.
     * Spring Security automatically adds the 'Content-Security-Policy' header.
     * With our policy: script-src 'self' 'nonce-{nonce}';
     * 1. Scripts from our own domain ('self') will run.
     * 2. Inline scripts with the correct nonce will run.
     * 3. Any other scripts (e.g., from CDN or inline without nonce) will be BLOCKED by the browser.
     */
    @GetMapping("/demo")
    public ResponseEntity<String> getCspDemo(HttpServletRequest request) {
        // Retrieve the nonce generated by CspNonceFilter for this request
        String nonce = (String) request.getAttribute("cspNonce");
        
        // If the classic attribute isn't found (depends on Spring version/config), 
        // Spring Security often places it in other attributes or we use a custom writer.
        // In modern Spring Security 6.x, we often access it via the request.
        
        String html = """
            <!DOCTYPE html>
            <html>
            <head>
                <title>CSP Demo</title>
            </head>
            <body>
                <h1>Content Security Policy Demo</h1>
                <p>Check the Browser Console (F12) to see what scripts were blocked.</p>
                
                <div id="status"></div>

                <!-- 1. This script has the CORRECT nonce and will run -->
                <script nonce="%s">
                    document.getElementById('status').innerHTML += '<p style="color:green">? SUCCESS: Inline script with correct nonce executed!</p>';
                </script>

                <!-- 2. This script HAS NO nonce and will be BLOCKED -->
                <script>
                    alert('This should NOT appear if CSP is working!');
                    document.getElementById('status').innerHTML += '<p style="color:red">? FAILURE: Inline script WITHOUT nonce executed!</p>';
                </script>

                <!-- 3. This script is from an EXTERNAL domain and will be BLOCKED -->
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            </body>
            </html>
            """.formatted(nonce != null ? nonce : "NONE_FOUND");

        return ResponseEntity.ok()
                .header("Content-Type", "text/html")
                .body(html);
    }
}
