# Scenario 20: Custom Properties
scenario20.app.name=The Debug Challenge - Externalized
scenario20.app.version=v2.0-CUSTOM
scenario20.app.description=This value was loaded using @PropertySource from a separate file!

# New for @ConfigurationProperties Demo
scenario20.server.host=127.0.0.1
scenario20.server.port=8081
scenario20.server.timeout=5000
